sensor:
  - platform: rest
    resource: http://yourserver:10453/state
    name: Desk Height
    timeout: 20
    unit_of_measurement: cm
    value_template: "{{ value_json.height / 10 }}"
    json_attributes:
      - position

rest_command:
  desk_sitting:
    url: http://yourserver:10453/state
    method: post
    timeout: 40
    content_type: "application/x-www-form-urlencoded"
    payload: "sit=true"
    
  desk_standing:
    url: http://yourserver:10453/state
    method: post
    timeout: 40
    content_type: "application/x-www-form-urlencoded"
    payload: "stand=true"

switch:
  - platform: template
    switches:
      standing_desk:
        friendly_name: Standing Desk
        value_template: "{{ is_state_attr('sensor.desk_height', 'position', 'standing') }}"
        turn_on:
          service: rest_command.desk_sitting
        turn_off:
          service: rest_command.desk_standing
        icon_template: >-
          {% if is_state('switch.standing_desk', 'on') %}
            hass:human-handsdown
          {% else %}
            hass:chair-rolling
          {% endif %}

homeassistant:
  customize:
    sensor.desk_height:
      icon: hass:ruler
